import {
  ReceiptOutlined,
  BarChartOutlined,
  MapOutlined,
  Groups,
  OndemandVideo,
  VideoCall,
  Web,
  Quiz,
  Wysiwyg,
  ManageHistory,
  Settings,
  ExitToApp,
  PeopleOutline,
  ArrowBackIos,
  ArrowForwardIos,
  HomeOutlined,
} from "@mui/icons-material";
export {
    ReceiptOutlined,
    BarChartOutlined,
    MapOutlined,
    Groups,
    OndemandVideo,
    VideoCall,
    Web,
    Quiz,
    Wysiwyg,
    ManageHistory,
    Settings,
    ExitToApp,
    PeopleOutline,
    ArrowBackIos,
    ArrowForwardIos,
    HomeOutlined
}